/*
 * EingabeDatenDialog.java
 *
 * Created on 23. März 2006, 09:42
 */
package vis2006;
import DatabaseManagement.*;
import java.sql.*;

/**
 *
 * @author  nagel
 */
public class EingabeDatenDialog extends javax.swing.JDialog {
    
    int lastAuf=0;
    int lastJahr=0;
    int lastMonat=1;
    double lastflha=0.0;
    int lastQualAuf = -1;
    String id="";
    Integer auf = 1;
    Integer jahr =2006;
    Integer monat =1;
    Double flha= 0.0;
    String typ="H";
    double altersDifferenz=0.0;
    String lokaleDB = "";
    
    
    /** Creates new form EingabeDatenDialog */
    public EingabeDatenDialog(java.awt.Frame parent, boolean modal, String idSelected, String lokaleDB) {
        super(parent, modal);
        id=idSelected;
        this.lokaleDB = lokaleDB;
        initComponents();
        getLetzteAuf();
        jLabel1.setText("ID: "+idSelected+" letze Aufn.: "+lastAuf+" Datum: "+lastMonat+"/"+lastJahr);
        auf = lastAuf+1;
        jTextField1.setText(auf.toString());
        jTextField2.setText("0");
        flha=lastflha;
        jTextField3.setText(flha.toString());

        setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Übernahme der Daten aus der Eingabetabelle");
        setModal(true);

        jPanel1.setLayout(new java.awt.GridLayout(5, 2));

        jLabel2.setText("Aufnahmetyp");
        jPanel1.add(jLabel2);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hauptaufnahme", "Nebenaufnahme", "Umfangmaßbandaufnahme" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);

        jLabel3.setText("Aufnahmenummer");
        jPanel1.add(jLabel3);

        jTextField1.setText("jTextField1");
        jPanel1.add(jTextField1);

        jLabel4.setText("Jahr");
        jPanel1.add(jLabel4);

        jTextField2.setText("jTextField2");
        jPanel1.add(jTextField2);

        jLabel5.setText("Monat");
        jPanel1.add(jLabel5);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jPanel1.add(jComboBox2);

        jLabel6.setText("Flächengröße in ha");
        jPanel1.add(jLabel6);

        jTextField3.setText("jTextField3");
        jPanel1.add(jTextField3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jButton1.setText("Daten einfügen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, java.awt.BorderLayout.SOUTH);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-400)/2, (screenSize.height-300)/2, 400, 300);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean datenok=true;
        switch(jComboBox1.getSelectedIndex()){
            case 0: typ="H"; break;
            case 1: typ="N"; break; 
            case 2: typ="U"; break;           
        }
        auf = Integer.parseInt(jTextField1.getText());
        if (auf <= lastAuf) datenok=false;
        jahr = Integer.parseInt(jTextField2.getText());
        if (jahr < lastJahr) datenok=false;
        monat = Integer.parseInt((String)(jComboBox2.getSelectedItem()));
        flha = Double.parseDouble(jTextField3.getText());
        if (flha <= 0.0) datenok=false;
        if (datenok == false) jButton1.setText("Eingabefehler, neuer Versuch");
        else {
            AltersDezimale aDez = new AltersDezimale(); 
            altersDifferenz= jahr+aDez.getAltersdezimale(monat)-(lastJahr+aDez.getAltersdezimale(lastMonat));
        addAuf();    
        dispose();
        }
        

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void getLetzteAuf(){
        DBConnection dbconn= new DBConnection(2);     // a class to manage the conection to a database
        dbconn.openDBConnection(DBConnection.ACCESS, 1, lokaleDB, "", "", false, true);
        Statement stmt = null;
        ResultSet rs = null;
        try{ 
// letzte Aufnahme feststellen
             stmt = dbconn.Connections[1].createStatement(); 
             rs = stmt.executeQuery("SELECT * FROM Auf WHERE edvid = \'"+id+"\' ORDER BY auf DESC");
             if (rs.next()) {
                 lastAuf=rs.getInt("auf");
                 lastJahr = rs.getInt("jahr");
                 lastMonat = rs.getInt("monat");
                 lastflha = rs.getDouble("flha");
                 lastQualAuf = rs.getInt("qualitat");
             }
        }
        catch (Exception e){  System.out.println(e); 
        } finally{
            try{
                if(rs != null) rs.close();
                if(stmt != null) stmt.close();                       
            } catch(Exception ex){}
        }
        dbconn.closeAll();

    }

    private void addAuf(){
        DBConnection dbconn= new DBConnection(2);     // a class to manage the conection to a database
        dbconn.openDBConnection(DBConnection.ACCESS, 1, lokaleDB, "", "", false, true);
        Statement stmt = null;
        try{ 
//  neue Aufnahme einfügen
            stmt = dbconn.Connections[1].createStatement(); 
            String neuid= auf.toString();
            if (neuid.length()==1) neuid="0"+neuid;
            neuid=id+neuid;
            String vs ="('"+neuid+"', '"+id+"', "+auf+", "+monat+", "+jahr+", "+flha.toString()+", "+lastQualAuf+", '"
                    +typ+"', '', '', '', 0)"; 
            System.out.println(vs);
            stmt.execute("INSERT INTO Auf  "+
                               "(id, edvid , auf, monat, jahr, flha, qualitat, typ, messh, repfac, bemerk, pz) "+
                               "VALUES "+vs);
            stmt.close();
            
            Eingabetabelle eingabetabelle = new Eingabetabelle(this, lokaleDB);
            String erfolg = eingabetabelle.addEingabeTabelle(id, altersDifferenz, auf);
            System.out.println(erfolg);
        }
        
        catch (Exception e){  e.printStackTrace(); 
        } finally{
            try{
                if(stmt != null) stmt.close();
            }catch(Exception e){}
        }
        dbconn.closeAll();
        
    }
 
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
    
}
